version: "3.8"
services:
  redis:
    image: redis:8.2
    ports:
      - "6379:6379"
  db:
    image: pgvector/pgvector:0.8.1-pg17-trixie
    container_name: bripath
    environment:
      POSTGRES_USER: bripathadmin
      POSTGRES_PASSWORD: bripathadmin123
      POSTGRES_DB: bripath
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
